### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by ahojcn** [NietzscheI/BHuman_codeRelease2016_Translation#1]
请问您的邮箱或者QQ是多少，想请教几个问题~

**Comment by NietzscheI** [comment]
qq:416566894




------------------ 原始邮件 ------------------
发件人: "刘你好"<notifications@github.com>;
发送时间: 2019年3月28日(星期四) 下午5:43
收件人: "NietzscheI/BHuman_codeRelease2016_Translation"<BHuman_codeRelease2016_Translation@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [NietzscheI/BHuman_codeRelease2016_Translation] 你好 (#1)




请问您的邮箱或者QQ是多少，想请教几个问题~
